apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "CHARTNAME.fullname" . }}
  labels:
    {{- include "CHARTNAME.labels" . | nindent 4 }}
spec:
  entryPoints:
  {{- if .Values.ingress.tls }}
    - websecure
  {{- else }}
    - web
  {{- end }}
  routes:
  {{- if .Values.ingress.hostname }}
    - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
  {{- else }}
    - match: PathPrefix(`{{ .Values.ingress.path }}`)
  {{- end }}
      kind: Rule
      services:
        - name: {{ include "CHARTNAME.fullname" . }}
          port: {{ .Values.service.port }}
      #middlewares:
      #  - name: {{ include "CHARTNAME.fullname" . }}
  {{- if .Values.ingress.tls }}
  tls:
    stores: default
  {{- end }}
